name: "OpenBeliever Backend Services"
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: mrtux
      POSTGRES_PASSWORD: mrtux360
      POSTGRES_DB: openbeliever-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data

  graph:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/mrtux360
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - graph_data:/data

networks:
  default:
    driver: bridge

volumes:
  db_data:
  cache_data:
  graph_data: